/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SprintsRouteImport } from './routes/sprints'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as HrRouteImport } from './routes/hr'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as TasksCreateRouteImport } from './routes/tasks.create'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as StoriesMyRouteImport } from './routes/stories.my'
import { Route as StoriesCreateRouteImport } from './routes/stories.create'
import { Route as StoriesAllRouteImport } from './routes/stories.all'
import { Route as StoriesStoryIdRouteImport } from './routes/stories.$storyId'
import { Route as DefectsCreateRouteImport } from './routes/defects.create'
import { Route as DefectsDefectIdRouteImport } from './routes/defects.$defectId'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintsRoute = SprintsRouteImport.update({
  id: '/sprints',
  path: '/sprints',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoriesRoute,
} as any)
const TasksCreateRoute = TasksCreateRouteImport.update({
  id: '/tasks/create',
  path: '/tasks/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesMyRoute = StoriesMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => StoriesRoute,
} as any)
const StoriesCreateRoute = StoriesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => StoriesRoute,
} as any)
const StoriesAllRoute = StoriesAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => StoriesRoute,
} as any)
const StoriesStoryIdRoute = StoriesStoryIdRouteImport.update({
  id: '/$storyId',
  path: '/$storyId',
  getParentRoute: () => StoriesRoute,
} as any)
const DefectsCreateRoute = DefectsCreateRouteImport.update({
  id: '/defects/create',
  path: '/defects/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DefectsDefectIdRoute = DefectsDefectIdRouteImport.update({
  id: '/defects/$defectId',
  path: '/defects/$defectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/board': typeof BoardRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/hr': typeof HrRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payroll': typeof PayrollRoute
  '/plugins': typeof PluginsRoute
  '/projects': typeof ProjectsRoute
  '/recruitment': typeof RecruitmentRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sprints': typeof SprintsRoute
  '/stories': typeof StoriesRouteWithChildren
  '/team': typeof TeamRoute
  '/defects/$defectId': typeof DefectsDefectIdRoute
  '/defects/create': typeof DefectsCreateRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories/all': typeof StoriesAllRoute
  '/stories/create': typeof StoriesCreateRoute
  '/stories/my': typeof StoriesMyRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/board': typeof BoardRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/hr': typeof HrRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payroll': typeof PayrollRoute
  '/plugins': typeof PluginsRoute
  '/projects': typeof ProjectsRoute
  '/recruitment': typeof RecruitmentRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sprints': typeof SprintsRoute
  '/team': typeof TeamRoute
  '/defects/$defectId': typeof DefectsDefectIdRoute
  '/defects/create': typeof DefectsCreateRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories/all': typeof StoriesAllRoute
  '/stories/create': typeof StoriesCreateRoute
  '/stories/my': typeof StoriesMyRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/board': typeof BoardRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/hr': typeof HrRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payroll': typeof PayrollRoute
  '/plugins': typeof PluginsRoute
  '/projects': typeof ProjectsRoute
  '/recruitment': typeof RecruitmentRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sprints': typeof SprintsRoute
  '/stories': typeof StoriesRouteWithChildren
  '/team': typeof TeamRoute
  '/defects/$defectId': typeof DefectsDefectIdRoute
  '/defects/create': typeof DefectsCreateRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories/all': typeof StoriesAllRoute
  '/stories/create': typeof StoriesCreateRoute
  '/stories/my': typeof StoriesMyRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/board'
    | '/dashboard'
    | '/employees'
    | '/hr'
    | '/leave'
    | '/login'
    | '/notifications'
    | '/payroll'
    | '/plugins'
    | '/projects'
    | '/recruitment'
    | '/reports'
    | '/settings'
    | '/sprints'
    | '/stories'
    | '/team'
    | '/defects/$defectId'
    | '/defects/create'
    | '/stories/$storyId'
    | '/stories/all'
    | '/stories/create'
    | '/stories/my'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/board'
    | '/dashboard'
    | '/employees'
    | '/hr'
    | '/leave'
    | '/login'
    | '/notifications'
    | '/payroll'
    | '/plugins'
    | '/projects'
    | '/recruitment'
    | '/reports'
    | '/settings'
    | '/sprints'
    | '/team'
    | '/defects/$defectId'
    | '/defects/create'
    | '/stories/$storyId'
    | '/stories/all'
    | '/stories/create'
    | '/stories/my'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/board'
    | '/dashboard'
    | '/employees'
    | '/hr'
    | '/leave'
    | '/login'
    | '/notifications'
    | '/payroll'
    | '/plugins'
    | '/projects'
    | '/recruitment'
    | '/reports'
    | '/settings'
    | '/sprints'
    | '/stories'
    | '/team'
    | '/defects/$defectId'
    | '/defects/create'
    | '/stories/$storyId'
    | '/stories/all'
    | '/stories/create'
    | '/stories/my'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  BoardRoute: typeof BoardRoute
  DashboardRoute: typeof DashboardRoute
  EmployeesRoute: typeof EmployeesRoute
  HrRoute: typeof HrRoute
  LeaveRoute: typeof LeaveRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PayrollRoute: typeof PayrollRoute
  PluginsRoute: typeof PluginsRoute
  ProjectsRoute: typeof ProjectsRoute
  RecruitmentRoute: typeof RecruitmentRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SprintsRoute: typeof SprintsRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  TeamRoute: typeof TeamRoute
  DefectsDefectIdRoute: typeof DefectsDefectIdRoute
  DefectsCreateRoute: typeof DefectsCreateRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksCreateRoute: typeof TasksCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprints': {
      id: '/sprints'
      path: '/sprints'
      fullPath: '/sprints'
      preLoaderRoute: typeof SprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/tasks/create': {
      id: '/tasks/create'
      path: '/tasks/create'
      fullPath: '/tasks/create'
      preLoaderRoute: typeof TasksCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/my': {
      id: '/stories/my'
      path: '/my'
      fullPath: '/stories/my'
      preLoaderRoute: typeof StoriesMyRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/stories/create': {
      id: '/stories/create'
      path: '/create'
      fullPath: '/stories/create'
      preLoaderRoute: typeof StoriesCreateRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/stories/all': {
      id: '/stories/all'
      path: '/all'
      fullPath: '/stories/all'
      preLoaderRoute: typeof StoriesAllRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/stories/$storyId': {
      id: '/stories/$storyId'
      path: '/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof StoriesStoryIdRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/defects/create': {
      id: '/defects/create'
      path: '/defects/create'
      fullPath: '/defects/create'
      preLoaderRoute: typeof DefectsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defects/$defectId': {
      id: '/defects/$defectId'
      path: '/defects/$defectId'
      fullPath: '/defects/$defectId'
      preLoaderRoute: typeof DefectsDefectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StoriesRouteChildren {
  StoriesStoryIdRoute: typeof StoriesStoryIdRoute
  StoriesAllRoute: typeof StoriesAllRoute
  StoriesCreateRoute: typeof StoriesCreateRoute
  StoriesMyRoute: typeof StoriesMyRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesStoryIdRoute: StoriesStoryIdRoute,
  StoriesAllRoute: StoriesAllRoute,
  StoriesCreateRoute: StoriesCreateRoute,
  StoriesMyRoute: StoriesMyRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  BoardRoute: BoardRoute,
  DashboardRoute: DashboardRoute,
  EmployeesRoute: EmployeesRoute,
  HrRoute: HrRoute,
  LeaveRoute: LeaveRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PayrollRoute: PayrollRoute,
  PluginsRoute: PluginsRoute,
  ProjectsRoute: ProjectsRoute,
  RecruitmentRoute: RecruitmentRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SprintsRoute: SprintsRoute,
  StoriesRoute: StoriesRouteWithChildren,
  TeamRoute: TeamRoute,
  DefectsDefectIdRoute: DefectsDefectIdRoute,
  DefectsCreateRoute: DefectsCreateRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksCreateRoute: TasksCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
